Record achievements even if all the output is not read.
- Ignore PIPE signals that may come through if the user quits out of the
  pager in commands like 'git log'.

diff --git a/git-achievements b/git-achievements
--- a/git-achievements
+++ b/git-achievements
@@ -480,6 +480,7 @@ ACTIONLOGFILE="$HOME/.git-achievements-action.log"
 ACHIEVEMENTSLOGFILE="$HOME/.git-achievements.log"
 
 if [ ! "$1" = "achievements" ] ; then
+    trap "" PIPE # don't fail if user doesn't read all the output
     git "$@"
     r=$?
     if [ ! ${r} -eq 0 ] ; then
